name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 1.0.0
homepage: https://github.com/freres-toque/esc_pos_bluetooth
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_basic:
    path: /Volumes/MI3-SSD/project/flutter/printer/flutter_bluetooth_basic

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
